[book]
authors = ["TrueBlocks"]
language = "en"
src = "src"
title = "trueblocks-dalleserver Book"

[output.html]
preferred-dark-theme = "ayu"
additional-js = ["right-menu.js"]
additional-css = ["right-menu.css"]
